### ISSUE TITLE
Plugin should be compiled for Java 7

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqa-json-plugin#4]
Currently the compiler setting specifies Java 8, for compatibility reasons it should be Java 7 as the plugin is included in the default distributions.

**Comment by obfischer** [comment]
Will be done this evening...

**Comment by obfischer** [comment]
Confirmed, but I don't know why. I will investigate it.

**Comment by obfischer** [comment]
I don't know why, but the effective configuration of the compiler plugin differs for the JSON plugin.

**Comment by obfischer** [comment]
Shame on me. Found it.

**Comment by obfischer** [comment]
Fixed. Thx!

**Comment by phoegon** [comment]
This reappeared, the 1.3 version is compiled for java 8 and won't run in java 7.

**Comment by DirkMahler** [comment]
The compiler settings have been fixed (again). There's now also a jQA check in place which verifies the correct setting in the future.
